### ISSUE TITLE
 OSError: libcudart.so.11.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by RajaIAB** [transcriptionstream/transcriptionstream#14]
I face the following error after uploading the test transcribe file.

```
ts-gpu                      | Starting new instance of transcribe_example.sh. Current count: 0
ts-gpu                      | --- transcribing /transcriptionstream/incoming/transcribe/test.wav...
ts-web                      | 10.10.20.153 - - [11/Jun/2024 13:07:32] "GET / HTTP/1.1" 200 -
ts-web                      | 10.10.20.153 - - [11/Jun/2024 13:07:32] "GET /static/styles.css HTTP/1.1" 304 -
ts-web                      | 10.10.20.153 - - [11/Jun/2024 13:07:32] "GET /static/gears.svg HTTP/1.1" 304 -
ts-web                      | 10.10.20.153 - - [11/Jun/2024 13:07:32] "GET /static/alerts.js HTTP/1.1" 304 -
ts-web                      | 10.10.20.153 - - [11/Jun/2024 13:07:32] "GET /static/fileHandling.js HTTP/1.1" 304 -
ts-web                      | 10.10.20.153 - - [11/Jun/2024 13:07:32] "GET /static/transcription.js HTTP/1.1" 304 -
ts-web                      | 10.10.20.153 - - [11/Jun/2024 13:07:32] "GET /static/audioControls.js HTTP/1.1" 304 -
ts-gpu                      | Traceback (most recent call last):
ts-gpu                      |   File "/usr/local/bin/whisperx", line 5, in <module>
ts-gpu                      |     from whisperx.transcribe import cli
ts-gpu                      |   File "/usr/local/lib/python3.10/dist-packages/whisperx/__init__.py", line 1, in <module>
ts-gpu                      |     from .transcribe import load_model
ts-gpu                      |   File "/usr/local/lib/python3.10/dist-packages/whisperx/transcribe.py", line 9, in <module>
ts-gpu                      |     from .alignment import align, load_align_model
ts-gpu                      |   File "/usr/local/lib/python3.10/dist-packages/whisperx/alignment.py", line 11, in <module>
ts-gpu                      |     import torchaudio
ts-gpu                      |   File "/usr/local/lib/python3.10/dist-packages/torchaudio/__init__.py", line 1, in <module>
ts-gpu                      |     from torchaudio import (  # noqa: F401
ts-gpu                      |   File "/usr/local/lib/python3.10/dist-packages/torchaudio/_extension/__init__.py", line 43, in <module>
ts-gpu                      |     _load_lib("libtorchaudio")
ts-gpu                      |   File "/usr/local/lib/python3.10/dist-packages/torchaudio/_extension/utils.py", line 61, in _load_lib
ts-gpu                      |     torch.ops.load_library(path)
ts-gpu                      |   File "/usr/local/lib/python3.10/dist-packages/torch/_ops.py", line 1032, in load_library
ts-gpu                      |     ctypes.CDLL(path)
ts-gpu                      |   File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
ts-gpu                      |     self._handle = _dlopen(self._name, mode)
ts-gpu                      | OSError: libcudart.so.11.0: cannot open shared object file: No such file or directory
ts-gpu                      | --- done processing /transcriptionstream/incoming/transcribe/test.wav - output placed in /transcriptionstream/transcribed/test_20240611130731
ts-gpu                      | transcription:  
ts-gpu                      | Runtime for processing /transcriptionstream/incoming/transcribe/test.wav = 2
ts-gpu                      | ------------------------------------
```

P.S: I have the NVIDIA ToolKit installed in my system.

```
(base) bash-4.4$ yum list installed | grep toolkit
cuda-toolkit-11-4.x86_64                           11.4.0-1                                      @cuda-rhel8-11-4-local                
cuda-toolkit-11-4-config-common.noarch             11.4.43-1                                     @cuda-rhel8-11-4-local                
cuda-toolkit-11-config-common.noarch               11.4.43-1                                     @cuda-rhel8-11-4-local                
cuda-toolkit-config-common.noarch                  11.4.43-1                                     @cuda-rhel8-11-4-local                
libnvidia-container-tools.x86_64                   1.15.0~rc.3-1                                 @nvidia-container-toolkit-experimental
libnvidia-container1.x86_64                        1.15.0~rc.3-1                                 @nvidia-container-toolkit-experimental
nvidia-container-toolkit.x86_64                    1.15.0~rc.3-1                                 @nvidia-container-toolkit-experimental
nvidia-container-toolkit-base.x86_64               1.15.0~rc.3-1                                 @nvidia-container-toolkit-experimental
```

**Comment by transcriptionstream** [comment]
looks a bit like there's an issue with GPU drivers/cuda. What does the following give you?

`sudo docker run --rm --runtime=nvidia --gpus all ubuntu nvidia-smi`

**Comment by transcriptionstream** [comment]
no response
